# Generated by Django 4.2 on 2023-04-03 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lightcommands',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date triggerd'),
        ),
    ]
